export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'
export const GET_SEARCH_PENDING = 'GET_SEARCH_PENDING'
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'

export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'

export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'
export const GET_PRODUCT_DETAIL_PENDING = 'GET_PRODUCT_DETAIL_PENDING'
export const GET_PRODUCT_DETAIL_ERROR = 'GET_PRODUCT_DETAIL_ERROR'

export const INSERT_PRODUCT_SUCCESS = 'INSERT_PRODUCT_SUCCESS'
export const INSERT_PRODUCT_PENDING = 'INSERT_PRODUCT_PENDING'
export const INSERT_PRODUCT_ERROR = 'INSERT_PRODUCT_ERROR'

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'